apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: novabank-web
  namespace: novabank
  labels:
    app: novabank-web
    owner: novabank
spec:
  replicas: 2

  selector:
    matchLabels:
      app: novabank-web

  template:
    metadata:
      labels:
        app: novabank-web
        owner: novabank

   spec:
      containers:
      - name: nginx
        image: nginx:1.26
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s

      - setWeight: 50
      - pause:
          duration: 30s

      - setWeight: 100